spring.application.name=Tienda
#De esta forma se define el puerto dondde escucha el servidor
server.port=80
#Definir el formato de despliegue de fecha y hora en los logs
logging.pattern.dateformat=hh:mm
#Eliminar logo de Spring
#spring.main.banner-mode=off